"""
Pytest regression tests for the metabolomics pipeline.

Re-runs each pipeline step on data/metabolomics_data.csv and checks that
the output matches the fixtures saved in tests/fixtures/ (generated by
create_fixtures.py).
"""
import json
import os
import sys

import pandas as pd
import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from tools.load_metabolomics_data import load_metabolomics_data
from tools.qc_filter import qc_filter
from tools.impute_missing import impute_missing
from tools.transform import transform
from tools.scale import scale
from tools.differential_abundance import differential_abundance

DATA_PATH = os.path.join(ROOT, "data", "metabolomics_data.csv")
METADATA_PATH = os.path.join(ROOT, "data", "sample_annotation.csv")
FIXTURES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")
GROUP_COLUMN = "DM_5crit"


def load_fixture(name):
    with open(os.path.join(FIXTURES_DIR, name)) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def loaded_df():
    return load_metabolomics_data(DATA_PATH)["dataframe"]


@pytest.fixture(scope="module")
def qc_df(loaded_df):
    return qc_filter(loaded_df)["dataframe"]


@pytest.fixture(scope="module")
def imputed_df(qc_df):
    return impute_missing(qc_df)


@pytest.fixture(scope="module")
def metadata():
    metadata_df = pd.read_csv(
        METADATA_PATH,
        index_col=0,
        na_values=['-', '.', 'NA', 'N/A', '']
    )
    if 'Sample name' in metadata_df.columns:
        metadata_df = metadata_df.set_index('Sample name')
    metadata_df.index = metadata_df.index.astype(str)
    return metadata_df


@pytest.fixture(scope="module")
def da_results(imputed_df, metadata):
    df = transform(imputed_df["dataframe"], "log")["dataframe"]
    df = scale(df)["dataframe"]
    return differential_abundance(df, metadata, GROUP_COLUMN)


def test_qc_filter_retains_same_metabolites(qc_df):
    expected = load_fixture("qc_output.json")["kept_metabolites"]
    assert list(qc_df.columns) == expected


def test_imputation_leaves_no_missing_values(imputed_df):
    expected = load_fixture("impute_output.json")
    assert imputed_df["missing_before"] == expected["missing_before"]
    assert imputed_df["missing_after"] == expected["missing_after"]
    assert imputed_df["dataframe"].isnull().sum().sum() == 0


def test_differential_abundance_finds_same_significant_metabolites(da_results):
    expected = load_fixture("da_output.json")["significant"]
    expected_metabolites = {row["metabolite"] for row in expected}

    significant = da_results["significant"]
    actual_metabolites = set(significant["metabolite"])

    assert actual_metabolites == expected_metabolites

    actual_by_name = significant.set_index("metabolite")
    for row in expected:
        assert actual_by_name.loc[row["metabolite"], "p_value"] == pytest.approx(row["p_value"], abs=1e-4)
        assert actual_by_name.loc[row["metabolite"], "fold_change"] == pytest.approx(row["fold_change"], abs=1e-4)
